In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Question 1

In [2]:
def save_csv(df: pd.DataFrame):
    temp_df = df.reset_index()
    temp_df.set_index('Name', inplace=True)
    temp_df.to_csv("/content/drive/MyDrive/DS-Lab-CS21B2018/SBIAccountHolder.csv")

sbi_acc = {
    "Account_No": [],
    "Name": [],
    "Account_Type": [],
    "Adhaar_No": [],
    "Balance": []
}

acc_df = pd.DataFrame(sbi_acc)
save_csv(acc_df)
print()
print("Data saved as 'SBIAccountHolder.csv': ")
print(acc_df)
acc_df.set_index("Account_No", inplace=True)

Data saved as 'SBIAccountHolder.csv':
Empty DataFrame
Columns: [Account_No, Name, Account_Type, Adhaar_No, Balance]
Index: []

In [3]:
print("1. Append record")
print("2. Delete Record")
print("3. Credit from the account")
print("4. Debit from the account")
print("5. Print account details")
print("6. Exit")
choice = 0

while choice != 6:
    choice = int(input("\nEnter Choice: "))

    if choice == 1:
        print("New Entry:")
        new_acc = int(input("\tAccount Number: "))

        new_entry = []
        new_entry.append(input("\tName: "))
        new_entry.append(input("\tAccount Type: "))
        new_entry.append(input("\tAdhaar No: "))
        new_entry.append(int(input("\tBalance: ")))

        acc_df.loc[new_acc] = new_entry
        save_csv(acc_df)
    
    elif choice == 2:
        acc_num = int(input("Enter the account number to delete: "))

        try:
            acc_df.drop(acc_num, inplace=True)
        except KeyError:
            print(f"Account no '{acc_num}' does not exist")
        
        save_csv(acc_df)
    
    elif choice == 3:
        acc_num = int(input("Enter the account number: "))

        amnt = int(input("\t Credit amount: "))
        if amnt < 0:
            print(f"Invalid Amount '{amnt}'")
            continue
        
        try:
            acc_df.loc[acc_num, "Balance"] += amnt
        except KeyError:
            print(f"Account no '{acc_num}' does not exist")
        
        save_csv(acc_df)
    
    elif choice == 4:
        acc_num = int(input("Enter the account number: "))

        amnt = int(input("\t Debit amount: "))
        if amnt < 0:
            print(f"Invalid Amount '{amnt}'")
            continue
        
        try:
            if acc_df.loc[acc_num, "Account_Type"] == 'SB' and amnt > acc_df.loc[acc_num, "Balance"]:
                print("Insufficient Balance")
            else:
                acc_df.loc[acc_num, "Balance"] -= amnt
        except KeyError:
            print(f"Account no '{acc_num}' does not exist")
        
        save_csv(acc_df)
    
    elif choice == 5:
        acc_num = int(input("Enter the account number: "))
        try:
            print(acc_df.loc[acc_num:acc_num])
        except KeyError:
            print(f"Account no '{acc_num}' does not exist")

    elif choice == 6:
        print("Exiting...")
    
    else:
        print("Invalid Choice")

1. Append record
2. Delete Record
3. Credit from the account
4. Debit from the account
5. Print account details
6. Exit

Enter Choice: 1
New Entry:
	Account Number: 9893893891
	Name: Ram
	Account Type: SB
	Adhaar No: 959389389173
	Balance: 8989839

Enter Choice: 1
New Entry:
	Account Number: 9893893898
	Name: Sam
	Account Type: CA
	Adhaar No: 959389389179
	Balance: 7690990

Enter Choice: 1
New Entry:
	Account Number: 9893893871
	Name: Prabhu
	Account Type: SB
	Adhaar No: 959389389159
	Balance: 989330

Enter Choice: 1
New Entry:
	Account Number: 9893893888
	Name: Preksha
	Account Type: CA
	Adhaar No: 959389389123
	Balance: 200301

Enter Choice: 3
Enter the account number: 9893893888
	 Credit amount: 200

Enter Choice: 4
Enter the account number: 9893893888
	 Debit amount: 400

Enter Choice: 5
Enter the account number: 9893893888
               Name Account_Type     Adhaar_No   Balance
Account_No
9893893888  Preksha           CA  959389389123  200101.0

Enter Choice: 2
Enter the account number to delete: 9893893888

Enter Choice: 6
Exiting...

### Question 2

In [4]:
num = int(input("Enter the number of accounts: "))
adhaar = {
    "Adhaar_No": [],
    "Name": [],
    "Contact_No": [],
    "DOB": [],
    "Address": []
}
for i in range(num):
    print(f"Entry{i+1}:")
    adhaar["Name"].append(input("\tName: "))
    adhaar["Adhaar_No"].append(int(input("\tAdhaar No: ")))
    adhaar["Contact_No"].append(int(input("\tContact No: ")))
    adhaar["DOB"].append(input("\tDOB: "))
    adhaar["Address"].append(input("\tAddress: "))

adhaar_df = pd.DataFrame(adhaar)
adhaar_df.set_index('Adhaar_No', inplace=True)
adhaar_df.to_csv("/content/drive/MyDrive/DS-Lab-CS21B2018/Adhaar_DB.csv")
print()
print("Data saved as 'Adhaar_DB.csv': ")
print(adhaar_df)

Enter the number of accounts: 3
Entry1:
	Name: Ram
	Adhaar No: 959389389173
	Contact No: 9840787333
	DOB: 12-2-1990
	Address: No 23, Kandigai, Chennai 127
Entry2:
	Name: Sam
	Adhaar No: 959389389179
	Contact No: 9840787343
	DOB: 12-2-2000
	Address: No 73, Melakottaiyur, Chennai 127
Entry3:
	Name: Prabhu
	Adhaar No: 959389389159
	Contact No: 9840787353
	DOB: 12-2-2010
	Address: No 43, Anna Nagar, Chennai 102

Data saved as 'Adhaar_DB.csv':
                Name  Contact_No        DOB                            Address
Adhaar_No
959389389173     Ram  9840787333  12-2-1990       No 23, Kandigai, Chennai 127
959389389179     Sam  9840787343  12-2-2000  No 73, Melakottaiyur, Chennai 127
959389389159  Prabhu  9840787353  12-2-2010     No 43, Anna Nagar, Chennai 102

### Merging two Tables

In [9]:
df1 = pd.read_csv("/content/drive/MyDrive/DS-Lab-CS21B2018/SBIAccountHolder.csv", index_col=None)

print(df1)

     Name  Account_No Account_Type     Adhaar_No    Balance
0     Ram  9893893891           SB  959389389173  8989839.0
1     Sam  9893893898           CA  959389389179  7690990.0
2  Prabhu  9893893871           SB  959389389159   989330.0

In [10]:
df2 = pd.read_csv("/content/drive/MyDrive/DS-Lab-CS21B2018/Adhaar_DB.csv", index_col=None)

print(df2)

      Adhaar_No    Name  Contact_No        DOB  \
0  959389389173     Ram  9840787333  12-2-1990
1  959389389179     Sam  9840787343  12-2-2000
2  959389389159  Prabhu  9840787353  12-2-2010

                             Address
0       No 23, Kandigai, Chennai 127
1  No 73, Melakottaiyur, Chennai 127
2     No 43, Anna Nagar, Chennai 102

In [11]:
print("Merging both the csv as 'MergeBankAdhaar.csv':")
comb_df = pd.merge(df1, df2, how='outer', on=['Adhaar_No', 'Name'])
print(comb_df)
comb_df.to_csv("/content/drive/MyDrive/DS-Lab-CS21B2018/MergeBankAdhaar.csv")

Merging both the csv as 'MergeBankAdhaar.csv':
     Name  Account_No Account_Type     Adhaar_No    Balance  Contact_No  \
0     Ram  9893893891           SB  959389389173  8989839.0  9840787333
1     Sam  9893893898           CA  959389389179  7690990.0  9840787343
2  Prabhu  9893893871           SB  959389389159   989330.0  9840787353

         DOB                            Address
0  12-2-1990       No 23, Kandigai, Chennai 127
1  12-2-2000  No 73, Melakottaiyur, Chennai 127
2  12-2-2010     No 43, Anna Nagar, Chennai 102